### ISSUE TITLE
Make this repo a Jekyll site that generates a GH Pages site

### ISSUE THREAD

**Issue by bmann** [ethereumclassic/ECIPs#10]
Hey all. The Ethereum main-net repo is formatted as a Jekyll site, so it can be hosted on Github Pages or elsewhere and be browsed as a website. This means making some formatting changes and a few other config files.

I know Jekyll and if this is of interest, I can put a bit of time into it.

**Comment by realcodywburns** [comment]
Yes i think this would make the process much more approachable

**Comment by YazzyYaz** [comment]
@bmann is this an example of minimal YAML header for each ECIP?
```YAML
---
layout: ecip
ecip: 1010
title: Delay Difficulty Bomb Explosion
author: Igor Artamonov <splix@ethereumclassic.org>
status: Final
type: Standard
created: 2016-09-13
---
```
